name: Validate Commit Messages

on: [push, pull_request]

jobs:
  validate_commit_messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all commits

      - name: Check for intrusive commands in commit messages
        run: |
          # Get the range of new commits in the push
          new_commits=$(git rev-list --no-merges ${{ github.event.before }}..${{ github.sha }})

          if [ -n "$new_commits" ]; then
            for commit in $new_commits; do
              if git log -1 --pretty=%B "$commit" | grep -q 'intrusive'; then
                echo "::error::Commit message for $commit contains intrusive content."
                exit 1
              fi
            done
          fi