name: Block Intrusive Commands
on: [pull_request]

permissions:
  contents: read

jobs:
  scan-code:
    name: Scan Code for Intrusive Commands
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all commits

      - name: Scan for Intrusive Commands
        run: |
          search_results=$(grep -ri --exclude-dir={.git,.github} --file=./.github/BLOCKED_PATTERNS.txt . || true)
          echo "Scanning for intrusive commands"
          if [[ -n "${search_results}" ]]; then
              echo "intrusive commands found in the following files:"
              echo "${search_results}"
              exit 1
          else
              echo "no intrusive commands found."
          fi